# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class AdlInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, adl: float=None):  # noqa: E501
        """AdlInner - a model defined in Swagger

        :param _date: The _date of this AdlInner.  # noqa: E501
        :type _date: str
        :param adl: The adl of this AdlInner.  # noqa: E501
        :type adl: float
        """
        self.swagger_types = {
            '_date': str,
            'adl': float
        }

        self.attribute_map = {
            '_date': 'Date',
            'adl': 'adl'
        }
        self.__date = _date
        self._adl = adl

    @classmethod
    def from_dict(cls, dikt) -> 'AdlInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The adl_inner of this AdlInner.  # noqa: E501
        :rtype: AdlInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this AdlInner.


        :return: The _date of this AdlInner.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this AdlInner.


        :param _date: The _date of this AdlInner.
        :type _date: str
        """

        self.__date = _date

    @property
    def adl(self) -> float:
        """Gets the adl of this AdlInner.


        :return: The adl of this AdlInner.
        :rtype: float
        """
        return self._adl

    @adl.setter
    def adl(self, adl: float):
        """Sets the adl of this AdlInner.


        :param adl: The adl of this AdlInner.
        :type adl: float
        """

        self._adl = adl
