# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class AdxInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, adx: float=None, dmx: float=None, dmn: float=None):  # noqa: E501
        """AdxInner - a model defined in Swagger

        :param _date: The _date of this AdxInner.  # noqa: E501
        :type _date: str
        :param adx: The adx of this AdxInner.  # noqa: E501
        :type adx: float
        :param dmx: The dmx of this AdxInner.  # noqa: E501
        :type dmx: float
        :param dmn: The dmn of this AdxInner.  # noqa: E501
        :type dmn: float
        """
        self.swagger_types = {
            '_date': str,
            'adx': float,
            'dmx': float,
            'dmn': float
        }

        self.attribute_map = {
            '_date': 'Date',
            'adx': 'ADX',
            'dmx': 'DMX',
            'dmn': 'DMN'
        }
        self.__date = _date
        self._adx = adx
        self._dmx = dmx
        self._dmn = dmn

    @classmethod
    def from_dict(cls, dikt) -> 'AdxInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The adx_inner of this AdxInner.  # noqa: E501
        :rtype: AdxInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this AdxInner.


        :return: The _date of this AdxInner.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this AdxInner.


        :param _date: The _date of this AdxInner.
        :type _date: str
        """

        self.__date = _date

    @property
    def adx(self) -> float:
        """Gets the adx of this AdxInner.


        :return: The adx of this AdxInner.
        :rtype: float
        """
        return self._adx

    @adx.setter
    def adx(self, adx: float):
        """Sets the adx of this AdxInner.


        :param adx: The adx of this AdxInner.
        :type adx: float
        """

        self._adx = adx

    @property
    def dmx(self) -> float:
        """Gets the dmx of this AdxInner.


        :return: The dmx of this AdxInner.
        :rtype: float
        """
        return self._dmx

    @dmx.setter
    def dmx(self, dmx: float):
        """Sets the dmx of this AdxInner.


        :param dmx: The dmx of this AdxInner.
        :type dmx: float
        """

        self._dmx = dmx

    @property
    def dmn(self) -> float:
        """Gets the dmn of this AdxInner.


        :return: The dmn of this AdxInner.
        :rtype: float
        """
        return self._dmn

    @dmn.setter
    def dmn(self, dmn: float):
        """Sets the dmn of this AdxInner.


        :param dmn: The dmn of this AdxInner.
        :type dmn: float
        """

        self._dmn = dmn
