# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class CciInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, cci: float=None):  # noqa: E501
        """CciInner - a model defined in Swagger

        :param _date: The _date of this CciInner.  # noqa: E501
        :type _date: str
        :param cci: The cci of this CciInner.  # noqa: E501
        :type cci: float
        """
        self.swagger_types = {
            '_date': str,
            'cci': float
        }

        self.attribute_map = {
            '_date': 'Date',
            'cci': 'cci'
        }
        self.__date = _date
        self._cci = cci

    @classmethod
    def from_dict(cls, dikt) -> 'CciInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cci_inner of this CciInner.  # noqa: E501
        :rtype: CciInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this CciInner.


        :return: The _date of this CciInner.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this CciInner.


        :param _date: The _date of this CciInner.
        :type _date: str
        """

        self.__date = _date

    @property
    def cci(self) -> float:
        """Gets the cci of this CciInner.


        :return: The cci of this CciInner.
        :rtype: float
        """
        return self._cci

    @cci.setter
    def cci(self, cci: float):
        """Sets the cci of this CciInner.


        :param cci: The cci of this CciInner.
        :type cci: float
        """

        self._cci = cci
