# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class EfiInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, efi: float=None):  # noqa: E501
        """EfiInner - a model defined in Swagger

        :param _date: The _date of this EfiInner.  # noqa: E501
        :type _date: str
        :param efi: The efi of this EfiInner.  # noqa: E501
        :type efi: float
        """
        self.swagger_types = {
            '_date': str,
            'efi': float
        }

        self.attribute_map = {
            '_date': 'Date',
            'efi': 'efi'
        }
        self.__date = _date
        self._efi = efi

    @classmethod
    def from_dict(cls, dikt) -> 'EfiInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The efi_inner of this EfiInner.  # noqa: E501
        :rtype: EfiInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this EfiInner.


        :return: The _date of this EfiInner.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this EfiInner.


        :param _date: The _date of this EfiInner.
        :type _date: str
        """

        self.__date = _date

    @property
    def efi(self) -> float:
        """Gets the efi of this EfiInner.


        :return: The efi of this EfiInner.
        :rtype: float
        """
        return self._efi

    @efi.setter
    def efi(self, efi: float):
        """Sets the efi of this EfiInner.


        :param efi: The efi of this EfiInner.
        :type efi: float
        """

        self._efi = efi
