# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Ema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: List[str]=None, close: List[float]=None, ema: List[float]=None):  # noqa: E501
        """Ema - a model defined in Swagger

        :param _date: The _date of this Ema.  # noqa: E501
        :type _date: List[str]
        :param close: The close of this Ema.  # noqa: E501
        :type close: List[float]
        :param ema: The ema of this Ema.  # noqa: E501
        :type ema: List[float]
        """
        self.swagger_types = {
            '_date': List[str],
            'close': List[float],
            'ema': List[float]
        }

        self.attribute_map = {
            '_date': 'Date',
            'close': 'Close',
            'ema': 'EMA'
        }
        self.__date = _date
        self._close = close
        self._ema = ema

    @classmethod
    def from_dict(cls, dikt) -> 'Ema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ema of this Ema.  # noqa: E501
        :rtype: Ema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> List[str]:
        """Gets the _date of this Ema.


        :return: The _date of this Ema.
        :rtype: List[str]
        """
        return self.__date

    @_date.setter
    def _date(self, _date: List[str]):
        """Sets the _date of this Ema.


        :param _date: The _date of this Ema.
        :type _date: List[str]
        """

        self.__date = _date

    @property
    def close(self) -> List[float]:
        """Gets the close of this Ema.


        :return: The close of this Ema.
        :rtype: List[float]
        """
        return self._close

    @close.setter
    def close(self, close: List[float]):
        """Sets the close of this Ema.


        :param close: The close of this Ema.
        :type close: List[float]
        """

        self._close = close

    @property
    def ema(self) -> List[float]:
        """Gets the ema of this Ema.


        :return: The ema of this Ema.
        :rtype: List[float]
        """
        return self._ema

    @ema.setter
    def ema(self, ema: List[float]):
        """Sets the ema of this Ema.


        :param ema: The ema of this Ema.
        :type ema: List[float]
        """

        self._ema = ema
