# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class ObvInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, obv: float=None):  # noqa: E501
        """ObvInner - a model defined in Swagger

        :param _date: The _date of this ObvInner.  # noqa: E501
        :type _date: str
        :param obv: The obv of this ObvInner.  # noqa: E501
        :type obv: float
        """
        self.swagger_types = {
            '_date': str,
            'obv': float
        }

        self.attribute_map = {
            '_date': 'Date',
            'obv': 'obv'
        }
        self.__date = _date
        self._obv = obv

    @classmethod
    def from_dict(cls, dikt) -> 'ObvInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The obv_inner of this ObvInner.  # noqa: E501
        :rtype: ObvInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this ObvInner.


        :return: The _date of this ObvInner.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this ObvInner.


        :param _date: The _date of this ObvInner.
        :type _date: str
        """

        self.__date = _date

    @property
    def obv(self) -> float:
        """Gets the obv of this ObvInner.


        :return: The obv of this ObvInner.
        :rtype: float
        """
        return self._obv

    @obv.setter
    def obv(self, obv: float):
        """Sets the obv of this ObvInner.


        :param obv: The obv of this ObvInner.
        :type obv: float
        """

        self._obv = obv
