# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class PvoInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, pvo: float=None, hist: float=None, sig: float=None):  # noqa: E501
        """PvoInner - a model defined in Swagger

        :param _date: The _date of this PvoInner.  # noqa: E501
        :type _date: str
        :param pvo: The pvo of this PvoInner.  # noqa: E501
        :type pvo: float
        :param hist: The hist of this PvoInner.  # noqa: E501
        :type hist: float
        :param sig: The sig of this PvoInner.  # noqa: E501
        :type sig: float
        """
        self.swagger_types = {
            '_date': str,
            'pvo': float,
            'hist': float,
            'sig': float
        }

        self.attribute_map = {
            '_date': 'Date',
            'pvo': 'PVO',
            'hist': 'HIST',
            'sig': 'SIG'
        }
        self.__date = _date
        self._pvo = pvo
        self._hist = hist
        self._sig = sig

    @classmethod
    def from_dict(cls, dikt) -> 'PvoInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The pvo_inner of this PvoInner.  # noqa: E501
        :rtype: PvoInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this PvoInner.


        :return: The _date of this PvoInner.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this PvoInner.


        :param _date: The _date of this PvoInner.
        :type _date: str
        """

        self.__date = _date

    @property
    def pvo(self) -> float:
        """Gets the pvo of this PvoInner.


        :return: The pvo of this PvoInner.
        :rtype: float
        """
        return self._pvo

    @pvo.setter
    def pvo(self, pvo: float):
        """Sets the pvo of this PvoInner.


        :param pvo: The pvo of this PvoInner.
        :type pvo: float
        """

        self._pvo = pvo

    @property
    def hist(self) -> float:
        """Gets the hist of this PvoInner.


        :return: The hist of this PvoInner.
        :rtype: float
        """
        return self._hist

    @hist.setter
    def hist(self, hist: float):
        """Sets the hist of this PvoInner.


        :param hist: The hist of this PvoInner.
        :type hist: float
        """

        self._hist = hist

    @property
    def sig(self) -> float:
        """Gets the sig of this PvoInner.


        :return: The sig of this PvoInner.
        :rtype: float
        """
        return self._sig

    @sig.setter
    def sig(self, sig: float):
        """Sets the sig of this PvoInner.


        :param sig: The sig of this PvoInner.
        :type sig: float
        """

        self._sig = sig
