# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class RocInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, roc: float=None):  # noqa: E501
        """RocInner - a model defined in Swagger

        :param _date: The _date of this RocInner.  # noqa: E501
        :type _date: str
        :param roc: The roc of this RocInner.  # noqa: E501
        :type roc: float
        """
        self.swagger_types = {
            '_date': str,
            'roc': float
        }

        self.attribute_map = {
            '_date': 'Date',
            'roc': 'roc'
        }
        self.__date = _date
        self._roc = roc

    @classmethod
    def from_dict(cls, dikt) -> 'RocInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The roc_inner of this RocInner.  # noqa: E501
        :rtype: RocInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this RocInner.


        :return: The _date of this RocInner.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this RocInner.


        :param _date: The _date of this RocInner.
        :type _date: str
        """

        self.__date = _date

    @property
    def roc(self) -> float:
        """Gets the roc of this RocInner.


        :return: The roc of this RocInner.
        :rtype: float
        """
        return self._roc

    @roc.setter
    def roc(self, roc: float):
        """Sets the roc of this RocInner.


        :param roc: The roc of this RocInner.
        :type roc: float
        """

        self._roc = roc
