openapi: 3.0.3
info:
  title: Stock Indicator Analysis Open API
  description: |-
    Stock Indicator Analysis API is used to get various stock indicator results based on the test required to be performed
    The API is to be consumed by the frontend team to display the charts required for the stock analysis and indicators
  version: 0.0.1
servers:
  - url: http://3.84.200.180/
security:
  - ApiKeyAuth: []
tags:
  - name: GeneralStockInfo
    description: Provide Candle stick data and general stock information
  - name: Overlays
    description:
      Technical indicators that use the same scale as prices are plotted
      over the top of the prices on a stock chart.
  - name: Oscillators
    description:
      Technical indicators that oscillate between a local minimum and maximum
      are plotted above or below a price chart.

paths:

#############################################
# Description of Paths for General Stock Info
#############################################

  /candlestick:
    get:
      tags:
        - GeneralStockInfo
      summary: The average price over the specified period
      operationId: calculate_candlestick
      parameters:
        - $ref: '#/components/parameters/symbol'
        - $ref: '#/components/parameters/start_date'
        - $ref: '#/components/parameters/period'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/candlestick"
        "401":
          description: API key is missing or invalid
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.general_stock_info_controller

#############################################
# Description of Paths for Overlays
#############################################

  /sma:
    get:
      tags:
        - Overlays
      summary: The average price over the specified period
      operationId: calculate_sma
      parameters:
        - $ref: '#/components/parameters/symbol'
        - $ref: '#/components/parameters/start_date'
        - $ref: '#/components/parameters/period'
        - $ref: '#/components/parameters/length_default_5'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sma"
        "401":
          description: API key is missing or invalid
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.overlays_controller
  /ema:
    get:
      tags:
        - Overlays
      summary: The average price over the specified period
      operationId: calculate_ema
      parameters:
        - $ref: '#/components/parameters/symbol'
        - $ref: '#/components/parameters/start_date'
        - $ref: '#/components/parameters/period'
        - $ref: '#/components/parameters/length_default_5'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ema"
        "401":
          description: API key is missing or invalid
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.overlays_controller
  /bollinger:
    get:
      tags:
        - Overlays
      summary:
        An oscillator meaning that it operates between or within a set range
        of numbers or parameters..
      operationId: calculate_bollinger_bands
      parameters:
        - $ref: '#/components/parameters/symbol'
        - $ref: '#/components/parameters/start_date'
        - $ref: '#/components/parameters/period'
        - $ref: '#/components/parameters/length_default_5'
        - $ref: '#/components/parameters/standard_deviation'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bollinger"
        "401":
          description: API key is missing or invalid
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.overlays_controller
  /psar:
    get:
      tags:
        - Overlays
      summary:
        An oscillator meaning that it operates between or within a set range
        of numbers or parameters..
      operationId: calculate_psar
      parameters:
        - $ref: '#/components/parameters/symbol'
        - $ref: '#/components/parameters/start_date'
        - $ref: '#/components/parameters/period'
        - $ref: '#/components/parameters/initial_acceleration'
        - $ref: '#/components/parameters/acceleration'                
        - $ref: '#/components/parameters/max_acceleration'                

      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/psar'
        "401":
          description: API key is missing or invalid
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.overlays_controller

#############################################
# Description of Paths for Oscillators
#############################################

  /cci:
    get:
      tags:
        - Oscillators
      summary: Used to help determine when an investment vehicle is reaching a condition of being overbought or oversold.
      operationId: calculate_cci
      parameters:
        - $ref: '#/components/parameters/symbol'
        - $ref: '#/components/parameters/start_date'
        - $ref: '#/components/parameters/period'
        - $ref: '#/components/parameters/length_default_14'
        - $ref: '#/components/parameters/cci_scaling_constant'        
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cci"
        "401":
          description: API key is missing or invalid
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller


  /mfi:
    get:
      tags:
        - Oscillators
      summary: The Money Flow Index (MFI) is an oscillator that uses both price and volume to measure buying and selling pressure over a specified period of time.
      operationId: calculate_mfi
      parameters:
        - $ref: '#/components/parameters/symbol'
        - $ref: '#/components/parameters/start_date'
        - $ref: '#/components/parameters/period'
        - $ref: '#/components/parameters/length_default_5'
        - $ref: '#/components/parameters/cci_scaling_constant'        
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mfi"
        "401":
          description: API key is missing or invalid
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller


  /efi:
    get:
      tags:
        - Oscillators
      summary: Elder's Force Index measures the power behind a price movement using price and volume as well as potential reversals and price corrections.
      operationId: calculate_efi
      parameters:
        - $ref: '#/components/parameters/symbol'
        - $ref: '#/components/parameters/start_date'
        - $ref: '#/components/parameters/period'
        - $ref: '#/components/parameters/length_default_13'
        - $ref: '#/components/parameters/cci_scaling_constant'        
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/efi"
        "401":
          description: API key is missing or invalid
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.oscillators_controller
################################
# Description of Components
################################

components:

################################
# Description of Response Schemas
################################

  schemas:
    candlestick:
      type: object
      properties:
        Date:
          type: array
          items:
            pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            type: string
            format: Date
            example: "2023-01-06, 2023-01-07"
        Close:
          type: array
          items:
            type: number
        Open:
          type: array
          items:
            type: number
        High:
          type: array
          items:
            type: number
        Low:
          type: array
          items:
            type: number
        Volume:
          type: array
          items:
            type: number
        AdjClose:
          type: array
          items:
            type: number
      example:
        Close:
          - 0.80
          - 0.80
        Open:
          - 0.80
          - 0.80
        High:
          - 0.80
          - 0.80
        Low:
          - 0.80
          - 0.80
        Volume:
          - 0.80
          - 0.80
        AdjClose:
          - 0.80
          - 0.80
        Date:
          - "2023-01-06, 2023-01-07"
          - "2023-01-06, 2023-01-07"
    sma:
      type: object
      properties:
        Date:
          type: array
          items:
            pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            type: string
            format: Date
            example: "2023-01-06, 2023-01-07"
        Close:
          type: array
          items:
            type: number
        SMA:
          type: array
          items:
            type: number
      example:
        SMA:
          - 6.027
          - 6.027
        Close:
          - 0.80
          - 0.80
        Date:
          - "2023-01-06, 2023-01-07"
          - "2023-01-06, 2023-01-07"
    ema:
      type: object
      properties:
        Date:
          type: array
          items:
            pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            type: string
            format: Date
            example: "2023-01-06, 2023-01-07"
        Close:
          type: array
          items:
            type: number
        EMA:
          type: array
          items:
            type: number
      example:
        EMA:
          - 6.027
          - 6.027
        Close:
          - 0.80
          - 0.80
        Date:
          - "2023-01-06, 2023-01-07"
          - "2023-01-06, 2023-01-07"
    bollinger:
      type: object
      properties:
        Date:
          type: array
          items:
            pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            type: string
            format: Date
            example: "2023-01-06, 2023-01-07"
        BBL:
          type: array
          items:
            type: number
        BBM:
          type: array
          items:
            type: number
        BBU:
          type: array
          items:
            type: number
        Close:
          type: array
          items:
            type: number
      example:
        BBU:
          - 1.46
          - 1.46
        Close:
          - 5.96
          - 5.96
        BBM:
          - 6.027
          - 6.02
        BBL:
          - 0.80
          - 0.80
        Date:
          - "2023-01-06, 2023-01-07"
          - "2023-01-06, 2023-01-07"

    psar:
      type: array
      items:
        type: object
        properties:
          Date:
            pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            type: string
            format: Date
            example: "2023-01-06"
          PSARl:
            type: number
            example: 145.02
          PSARs:
            type: number
            example: 154.02
          PSARaf:
            type: number
            example: 0.1
          PSARr:
            type: integer
            example: 1

    cci:
      type: array
      items:
        type: object
        properties:
          Date:
            pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            type: string
            format: Date
            example: "2023-01-06"
          cci:
            type: number
            example: 145.02

    cmf:
      type: array
      items:
        type: object
        properties:
          Date:
            pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            type: string
            format: Date
            example: "2023-01-06"
          cmf:
            type: number
            example: 145.02

    efi:
      type: array
      items:
        type: object
        properties:
          Date:
            pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            type: string
            format: Date
            example: "2023-01-06"
          efi:
            type: number
            example: 145.02

    mfi:
      type: array
      items:
        type: object
        properties:
          Date:
            pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            type: string
            format: Date
            example: "2023-01-06"
          mfi:
            type: number
            example: 145.02

################################
# Description of Responses
################################

  responses:
    UnauthorizedError:
      description: API key is missing or invalid
    NotFound:
      description: The specified symbol was not found

################################
# Description of Parameters
################################

  parameters:
    symbol:
      name: symbol
      in: query
      description: Ticker Symbol Required
      required: true
      style: form
      explode: true
      schema:
        type: string
    start_date:
      name: start_date
      in: query
      description: Start Date of Analysis in YYYY-MM-DD Format
      required: true
      style: form
      explode: true
      schema:
        pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
        type: string
        format: Date
        example: 2019-05-17T00:00:00.000Z
    end_date:
      name: end_date
      in: query
      description: End Date of Analysis in YYYY-MM-DD Format
      required: true
      style: form
      explode: true
      schema:
        pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
        type: string
        format: Date
        example: 2019-05-17T00:00:00.000Z
    period:
      name: period
      in: query
      description: The Analysis Period in Days from Start Date
      required: true
      style: form
      explode: true
      schema:
        minimum: 1
        type: integer
    length_default_5:
      name: length
      in: query
      description: The short period
      required: false
      style: form
      explode: true
      schema:
        type: integer
        default: 5
    standard_deviation:
      name: standard_deviation
      in: query
      description: The long period
      required: false
      style: form
      explode: true
      schema:
        type: integer
        default: 2
    initial_acceleration:
      name: initial_acceleration
      in: query
      description: The psar initial acceleration
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 0.02        
    acceleration:
      name: acceleration
      in: query
      description: The psar acceleration
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 0.02        
    max_acceleration:
      name: max_acceleration
      in: query
      description: The psar max acceleration
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 0.2 
    cci_scaling_constant:
      name: cci_scaling_constant
      in: query
      description: scaling constant
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 0.015
    length_default_14:
      name: length
      in: query
      description: period length
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 14
    length_default_13:
      name: length
      in: query
      description: period length
      required: false
      style: form
      explode: true
      schema:
        type: number
        default: 13
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-KEY
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_ApiKeyAuth